### ISSUE TITLE
Re-light Lutris

### ISSUE THREAD

**Issue by clydemcqueen** [zhrandell/Seattle_Aquarium_CCR_development#34]
_The problem_

Lutris (our primary research ROV) can take 4 high-lumen dive lights to provide lighting during surveys. Each light requires a battery, which should be changed for every transect. This lighting system slows down operations and adds unnecessary weight and bulk to the vehicle.

_The proposed solution_

Install 4 semi-permanent high-lumen subsea lights on Lutris. Each light should draw power from the existing Outland power system. Provide a way to control these lights remotely from the surface.

- [x] select and order lights
- [x] build a bench system with power supply and cables
- [x] write a Lua script to provide control
- [x] order enclosure parts
- [x] build enclosure
- [x] final install
- [ ] field test

**Comment by zhrandell** [comment]
Thanks for starting this Issue, Clyde! 

The lights we ordered are [DeepSea's LSL-2075 SeaStrobe](https://www.deepsea.com/led-sealite/lsl-2075-seastrobe/). The tighter beam angle (75 degrees, relative to the 120 degree angle of our current [Kraken solarflare](https://opticaloceansales.com/products/kraken-solarflare-mini18-video-light-18-000-lumens?srsltid=AfmBOor8inXwnp1JN3ygjitSswtwE2ty7bk0TBS-fdgQP_XCvb5xUud_) ROV lights) will more efficiently utilize the available lumens; the reduced backscatter (via less beam overlap) may enable ROV surveys in more turbid, algal-bloom type conditions than we normally work given the equipment we currently have. 

Additionally, as the lights can also function as a strobe, a ways down the road, if and when we eventually upgrade our cameras, we could synchronize the strobes and cameras.

**Comment by keenanjohnson** [comment]
We talked about this today during our call and I'll be taking the next steps! Collating a few pieces of information here first before I dig in. Firstly, we should write up a proper design including options for the voltage conversion and control for the operator of the lights.

Clyde had started this document: https://docs.google.com/document/d/16NcSzliwcoVw-hOqcO_qJ2WcCUVmne0_NP0diOatpmw/edit?tab=t.0#heading=h.6ra6x9yfbam4

Current vehicle voltage is stepped down from the tether 400 V to 15 V.

According to the datasheet we need to boost the light voltage over 20V to achieve the full output. 

At 24 V, we need ~100 Watts per light, so we are probably looking at a boost converter rated at 500 to 600 watts ish. 

<img width="978" height="738" alt="Image" src="https://github.com/user-attachments/assets/83e82a1b-10d1-4bed-b6c9-8ce889534c87" />

**Comment by zhrandell** [comment]
Thank you for helping us with this, @keenanjohnson!

**Comment by keenanjohnson** [comment]
Ok I've done some research on voltage boost converters, and there seem to be a few promising options. There is a reputable larger option and less reputable smaller option. 

## Reputable Option

Reputable option: [Victron Orion 12/24-20 ](https://bluemarine.com/products/victron-orion-dc-dc-converters-non-isolated-high-power?variant=45570200371496&country=US&currency=USD&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic&srsltid=AfmBOoqxiMAVKdCIZJ-2lcFcJHkn_nCr15YAp-mdxPI53jr805urKQJPoe4&com_cvv=8fb3d522dc163aeadb66e08cd7450cbbdddc64c6cf2e8891f6d48747c6d56d2c&gclid=CjwKCAiAl-_JBhBjEiwAn3rN7SeFhrb4K4vvgr4h8zxlylDVjZ1Ehr0n49hcq7PCesAQZAENxEUuMBoCQo8QAvD_BwE)

This unit is rated at 480 watts which should be sufficient for our purposes and victron is a very reputable brand with good quality converters in large temperature range swings. 

However it is pretty large: 65 mm x 88 mm x 195 mm 

<img width="986" height="714" alt="Image" src="https://github.com/user-attachments/assets/2bbcfd44-5c34-442d-a965-dd778b5cf8ac" />

## A less reputable option, but smaller

The ATO Model No.:WG-12S2420 does also seem to fulfill all the requirements, though this brand is certainly less reputable. However, it's main advtange is that it's much smaller than the victron unit: 72 mm x 80 mm x 100 mm

<img width="663" height="561" alt="Image" src="https://github.com/user-attachments/assets/3877ed64-ae22-4d22-9d1a-e7fba16adb87" />

https://www.ato.com/dc-dc-boost-converter-12v-to-24v?srsltid=AfmBOooKYfjFEHA0ug898WvRiUtnM6yRI-xV_TyuAwJLXkbCVP-9HEEf

<img width="667" height="721" alt="Image" src="https://github.com/user-attachments/assets/bda2f9e1-893a-41ec-969e-b930c9250e06" />

## Enclosures

Previously we had spec 'd out one of the Blue Robotics Boxes 

https://bluerobotics.com/store/watertight-enclosures/watertight-boxes/watertight-box/

The ATO above would fit in the 1 liter Blue Box, but the Victron would need the 5 Liter box. 

<img width="1293" height="539" alt="Image" src="https://github.com/user-attachments/assets/dc766a52-9ec2-497d-b7c6-540de8e422a6" />

Now I am worried that even though the ATO option would technically fit in the 1 liter box, I think it would just barely be there and I haven't accounted for any control electronics to dim the lights or harness space yet. 

However, @zhrandell is it actually feasible to have the 5 liter box on the ROV 322 x 212 x 113 mm or would a tube form factor be better?

**Comment by keenanjohnson** [comment]
Also is the pinout of the Sealite's serial port documented somewhere? I can't find anything in the datasheet, I just see one pin that's listed as the 4-20 mA control, but I thought you mentioned serial control on our call @clydemcqueen ?

**Comment by zhrandell** [comment]
<p align="center">
  <img src="https://github.com/user-attachments/assets/21889a99-7028-4ee9-bde0-4cbd5f48e1d3" width="40%" />
</p>

<p align="center">
  <img src="https://github.com/user-attachments/assets/e9f503a0-ed2e-4ff0-9042-923284d873ce" width="40%" />
  <img src="https://github.com/user-attachments/assets/b59a7a09-25cf-4715-acb5-4e6e12567d1a" width="40%" />
</p>

Hey @keenanjohnson, check out the attached photos. I'm thinking we can place a box or tube towards the rear of the vehicle (similar to where the Xbox controller box is placed). The two small metal horizontal poles can be moved / removed if necessary. 

We also have the GoPro camera mounts down on the lower payload skid, but those could be switched to the front of the skid, such that the cameras are still mostly centered, but face backwards (then we'd flip the orientation of the camera feed).

The small 1L box fits easily - no problemo. 

The 5L box might be a challenge. Ideally, we'd place it such that the longest axis spans the width between the payload skid. Unfortunately, with a 12.7 inches total external width for the 5L, it won't fit snugged horizontally into the rear space, as there's only about 12.5 inches available inbetween the payload skid (so close!!). Alternatively, having the longest axis placed length-wise along the payload skid would probably take up to much room . . . I think it's likely to extend into the area where we need the down-facing cameras to be. 

I guess if the 5L was well and truly the absolute best choice, we could potentially hack up the payload skid frame and the HDPE panels we've added to allow the 12.7 inches, though that's a less preferable -- but possible -- option. 

And re: Victron vs the ATO . . . all the components for the Aquarium's power supply powering the ROV system are Victron, and we're very happy with it - it's clearly excellent hardware, though it comes at the cost of size, as you note. Tradeoffs . . .

**Comment by clydemcqueen** [comment]
Hi, Keenan -- I just forwarded (in Outlook and Gmail) the various emails we had with Outland and DeepSea. The serial protocol is spelled out here: https://www.deepsea.com/seasense-protocol/

**Comment by keenanjohnson** [comment]
Thank you @clydemcqueen ! I see that and that just helps confirm the pinout which is useful for the next stage. I also found this python library from our friends at APL that implements the LED light serial protocol: https://gitlab.com/apl-ocean-engineering/pydspl_seasense/-/tree/main?ref_type=heads

@zhrandell yes that's helpful on the placement / enclosure constraints. My thought is that we rule out the victron device for now, as it can't fit inside the smaller enclosure and at least for now pencil in the ATO device as our notional plan. My next step there is probably to do a rough CAD with the microcontroller for serial control and wiring to make sure that it will actually fit in the 1 L box before we purchase.

If the ATO device seems to be bad or unreliable, I think the next most promising option would be a custom circuit board that uses this module (was suggested by someone from https://poseidonrov.com/ on linked). This could be nice as an eventual project since we could combine the boost conversion, serial, control and power monitoring into one board theoretically, but that feels like more of a medium / longer term project rather than something we could do in January for example.

**Comment by keenanjohnson** [comment]
Ok so a quick CAD check it does seem like there should be plenty of room for the ATO converter and some additional connection wires and a control microcontroller on the top of the converter in the box.

<img width="745" height="566" alt="Image" src="https://github.com/user-attachments/assets/c6f995cb-5ab1-48c6-bcf2-84122c092bad" />

<img width="871" height="620" alt="Image" src="https://github.com/user-attachments/assets/c3f624c8-f814-479a-a56f-b56c0278bb70" />

<img width="1050" height="826" alt="Image" src="https://github.com/user-attachments/assets/92c48deb-1128-444c-9c3f-5b7cf5285b73" />

**Comment by keenanjohnson** [comment]
I also made this proposed block diagram which includes the 6 penetrators we will need and the control electronics for the LEG control, and a current monitor so that we can monitor the power usage of the light subsystem and regulate the light power accordingly.

<img width="1689" height="489" alt="Image" src="https://github.com/user-attachments/assets/8fdd2a72-7623-458f-92a6-539f729243b3" />

How does this look to everyone? Am I forgetting anything?

**Comment by zhrandell** [comment]
This looks great, Keenan - thank you! I don't have the subject matter expertise to evaluate the wire diagram. Re: the housing and the ATO, it sounds like you're confident there will be enough room for everything? I don't have the intuition to guide how much space the wires require, etc., but based on the below image from the BR webpage, we can have everything snugged in rather cozy. Let me know when you're ready for parts to be oredered and we'll make it happen! 

<img width="1620" height="1022" alt="Image" src="https://github.com/user-attachments/assets/9406fe11-b5fb-4bb8-bea7-be1efcbc9c6f" />

**Comment by keenanjohnson** [comment]
Great. I'll put together a full parts list for your review @zhrandell if this all seems agreeable. In terms of wires / terminal blocks etc for wiring inside the box, do you all have stock of things on hand or should I spec everything out there in a BOM?

**Comment by zhrandell** [comment]
Sounds great, thanks @keenanjohnson! 

We have 26 AWG in red and black, and lots of small wires, their connectors, heat-shrink tubes (mostly for the small wire work necessary to install the DVL). We have lots of solder and a soldering kit. 

We also have all the pig-tails associated with the DeepSea lights. 

If we need it to connect everything properly in the box, we should probably add it to the list and I'll purchase it all.

**Comment by keenanjohnson** [comment]
Sounds good. I'll finalize selection of the smaller components today. @clydemcqueen are you aligned with the selection of one of the raspberry pi microcontrollers in the diagram above to do the control? We would need to write some software to interface with ardusub and then the lights, but I think that is worth it for the reduction and cabling complexity.

**Comment by keenanjohnson** [comment]
The raspberry pi picos have good micropython support and from my initial read, I think we can convert a version of the APL library to work with micropython quite easily. https://gitlab.com/apl-ocean-engineering/pydspl_seasense/-/tree/main?ref_type=heads

**Comment by clydemcqueen** [comment]
Amazing progress! W00t! I was initially a bit worried about programming the microcontroller, but that was before you found the APL driver. And with you in the lead I am way more confident. :-) Full steam ahead! @keenanjohnson

**Comment by keenanjohnson** [comment]
Hey all! I've put together the prelimary parts list which I think has everything important that we need from above. The only thing I didn't include was a terminal block for connecting all the LED power wires, which should be easy to find or I can bring over some extras if we don't have them on hand in the ROV shop.

The bom is available here or in the attached csv. 

https://docs.google.com/spreadsheets/d/19Hz08fuoHUxyz5qoto0jLs2NBdmtDjjIWauKPWLxyBg/edit?gid=0#gid=0

Let me know what you think! 

[Lutris Light Box BOM - Sheet1.csv](https://github.com/user-attachments/files/24229518/Lutris.Light.Box.BOM.-.Sheet1.csv)

**Comment by zhrandell** [comment]
Thank you so much, @keenanjohnson, for identifying all of these parts! We'll get them ordered. I too am not sure precisely the size of the pigtails, but we'll figure that out and will order the appropriate wetlink penetrators. Thanks again!

**Comment by m-h-williams** [comment]
@keenanjohnson I'm ordering the parts on the list you shared. 

Could you clarify which terminal blocks we need? The output wires from the Voltage Booster Converter are 14 AWG, while the individual wires inside the LED light multi-core cables appear to be 18 AWG.

Do you want a terminal block that combines all LED wires into a single connection (in series)? If so, how many positions should it have?

Or should we use one block for positive and another for negative power connections? In that case, would two of [these](https://www.adafruit.com/product/5616) work?

**Comment by keenanjohnson** [comment]
Yes @m-h-williams ! I wasn't too specific as we can use a lot of things. We just need something to connect the single positive and ground wires coming out of the converter to each of the 4 power and grounds of the LEDs. These snap connectors you linked are awesome and as long as the wire gauge we have will fit in them, they would work well!

**Comment by m-h-williams** [comment]
Great! Then robotics santa has finished purchasing everything on the list

**Comment by keenanjohnson** [comment]
Thank you! Perhaps sometime after the holidays we can have a bench day of wiring everything up and doing our first bench tests with just the LEDs / converter before installing it all on Lutris as @clydemcqueen suggested originally in this post! 

<img width="512" height="495" alt="Image" src="https://github.com/user-attachments/assets/8f83aeac-5e47-4589-a943-f5b5b917965b" />

**Comment by keenanjohnson** [comment]
I created https://github.com/Seattle-Aquarium/CCR_ROV_survey_methods/issues/23 to track the software development for the microcontroller.

**Comment by zhrandell** [comment]
Yay, thanks @keenanjohnson! And just a quick note that we've received all the hardware components that we ordered! We should be ready to bench test whenever you are.

**Comment by keenanjohnson** [comment]
We had a good day of initial wiring and testing of the new lights system!

We successfully tested that:

1. The voltage converted did function as intended!
2. The micropython script ran on the microcontroller (raspberry pi pico) 
3. All the hardware fit well inside the current enclosure (if we choose to stick with this one)
4. One light at max power drew around 98 Watts

We hit two small hicups:

1. I had forgotten to add the RS-485 transceiver to the BOM. That's been resolved and added here: https://github.com/Seattle-Aquarium/CCR_ROV_survey_methods/issues/32

2. The WAGO connector blocks we were using were too small for the input side wires of the current monitor. I'll try to find a few larger ones that we can add to the BOM and use for the input connection

![Image](https://github.com/user-attachments/assets/f9636180-de7d-4b64-a5b9-dd363ddc7206)

![Image](https://github.com/user-attachments/assets/47e0186c-6e4f-4afd-9d03-27240b21e4ad)

![Image](https://github.com/user-attachments/assets/7a382e42-92b1-46f7-81ec-b5c17287f92d)

**Comment by keenanjohnson** [comment]
I did a verification of the pwm code on my bench today with a pwm servo tester which emulates the pwm output of the ROV.

https://github.com/user-attachments/assets/7e1532b5-9fb0-4e25-a830-6aa6d1d5d49e

**Comment by keenanjohnson** [comment]
Just updating this thread since we haven't touched it in a while. 

We had a very successful day testing last week and fully demonstrated PWM control <-> to the raspberry pi microncontroller <--> the full deepsea lights last week on the bench.

We ran into some minor wiring challenges attempting to get everything to fit into the enclosure, but we are working through that now.

To help, I have added some additional documentation on the pins / what to connect to what in this PR and the readme of the ROV methods repo: https://github.com/Seattle-Aquarium/CCR_ROV_survey_methods/pull/38

**Comment by keenanjohnson** [comment]
These docs can now be found at : https://github.com/Seattle-Aquarium/CCR_ROV_survey_methods/tree/main/lighting/hardware

**Comment by zhrandell** [comment]
Noting here that per https://github.com/Seattle-Aquarium/CCR_ROV_survey_methods/issues/24, the physical mounting of the DeepSea lights and the 1L box has been successfully resolved. 

I now believe we're ready to perform the final DeepSea light installation and assembly within the box. I have the [T200 Thruster cable](https://bluerobotics.com/store/cables-connectors/high-temperature-pur-subsea-cable/) for power, and I have some [Lumen/Gripper cable](https://bluerobotics.com/store/cables-connectors/pur-subsea-cable/) for the PWM data cable (we also have some High Power Cable and Ethernet and Power Cable just to have on-hand for the future). 

One item to note re: the DeepSea cabling: 

- the 8.5mm LC WLP provided what appears to be appropriate compression to seal the DeepSea light cable (image below) when examined after 12 hours. 
- however, I want to flag here that only x4 of the DeepSea wires are able to be threaded through the 8.5mm WLP - we are fine to cut away the Red Light Chassis, though we also needed to cut down the Green Pulse / strobe. I was able to get x5 wires through the 8.5mm LC WLP by twisting them together and heat-shrinking them, but it was forced and I'm not 100% I didn't damage some insulation. We cannot increase WLP size without also needing to switch enclosures (as the 9.5mm WLP - the larger (and largest) size - requires bigger holes than the 1L box supports. 
- Given the DeepSea lights have strobe capability and we might explore this down the road, I decided to retain much of the 2m pigtail length so that we can bring the strobe functionality online - if desired - down the road.

<p align="center">
  <img src="https://github.com/user-attachments/assets/e01508d5-f533-4348-aa18-2725628a9329" width="40%" />
</p>

**Comment by zhrandell** [comment]
I'm very pleased to report that I've been able to fully wire and install the four DeepSea lights and the required microcontroller boards / conductors into the 1L BR box! 

I have the power and PWM signaling coming in through two ports in the bottom (with a vent plug and single blanking plug to round out the bottom row), and then I have all four lights entering the box via the top row of four ports. 

The power cables fold nicely underneath the x4 light WLPs, and I used wago connectors for most all other connections . . . the entire system can easily be connected/disconnected if required. 

It all fits within the box reasonably well - I didn't need to glue anything. The biggest obstacle is corralling all the wires such that the box lid doesn't squish any of them, but there appears to be enough space overall. 

The only wrinkle is that while the main electronics tube and battery tube are holding vacuum well, I dropped 1" of Hg when vacuum testing the box + main electronics tube. Today I'll open the box back up, check the main lid o-ring, etc. today and re-test. Hopefully that resolves it - I was pretty careful when adding the WLPs to the cables and likewise when installing the WLPs into the box, so I'm hoping the lid is the issue and that I can resolve it. I'll also add a dessicant pack into the box today. If tinkering with the lid doesn't resolve the slow leak, I'll presurize the box, apply soapy water, and will attempt to locate an issue with the WLPs. 

Photos below, including a video of the PWM signaling coming from the Xbox controller (servo 15 is mapped to the left and right d-pad buttons, such that we can increase brightness by increments of 10% with the controller). 

<p align="center">
  <img src="https://github.com/user-attachments/assets/0b7e3888-7a0d-45d2-abb3-b3a0bb3a06f6" width="40%" />
  <img src="https://github.com/user-attachments/assets/c06abe70-986d-435e-8fe9-e05baa4099c8" width="40%" />
</p>

<p align="center">
  <img src="https://github.com/user-attachments/assets/449c55cc-45fe-4034-8636-20a0765b883a" width="40%" />
  <img src="https://github.com/user-attachments/assets/f70a3b70-4b8f-46bb-9f05-90016cc8cd8e" width="40%" />
</p>

<p align="center">
  <img src="https://github.com/user-attachments/assets/8397242b-b396-4143-b504-92c2b2a3d686" width="40%" />
</p>

https://github.com/user-attachments/assets/daed26f9-1848-4b5c-a3a9-411ef1afecf1

**Comment by keenanjohnson** [comment]
This is excellent and great work on the wiring. Let me know if there are any software changes we would need to make and I can walk you through them in the future. 

Also, as I mentioned in working on a custom PCB to simplify the wiring, I had mentioned that we could have the option of having connections go out of the side of the board or vertically. Based on your wiring experience @zhrandell, do you have any better sense of what would be best?

**Comment by zhrandell** [comment]
Thanks, @keenanjohnson! After going through the full wiring and packing process within the 1L box, I believe side connectors make the most sense, as doing so would enable the wires to sit mostly flush down within the box. I *might* have to the lengthen the wires a bit for the two lights that plug in on the far side away from the Wet Link Penetrators (as those two light wires will have to traverse the width of the box prior to turning around and plugging into the far side of the new board), but that's a relatively minor adjustment, and I anticipated having to modify wiring a bit down the road anyways. That board will be a huge upgrade to enable other folks to easily replicate this hardware - thanks for leading the charge, Keenan! :-)

In other news, the 1 inHg drop in vacuum has been resolved. Something worth noting here (as I don't see it in the Blue Robotics documentation) is that if you plug the vacuum pump directly into the 1L box (and no other enclosures), it will drop vacuum quickly due to air entering the box via the numerous cables. If we plug into the 1L box and, e.g., the main enclosure tube, the rate of vacuum drop decreases, but as there are cabled connections between the main enclosure and the battery enclosure (which we're not plugged into), we still see a small drop in inHg. 

The fix, which @m-h-williams put forward, is to plug into both the 1L box and the main enclosure, pull a vacuum to 15 inHg, allow the relatively small drop in inHg to settle out, and then re-pump to 15 inHg . . . once we did so, we kept the 15 inHg nice and stable for the desired time. 

I therefore believe we're ready to test fly Lutris underwater (!!), and we tenatively plan to do so -- along with divers to take photos of the new configuration for our field methods manuscript -- tomorrow (4/2) AM!

**Comment by zhrandell** [comment]
Megan, Reid, and I had quite the eventful dive / ROV flight this morning with Lutris! 

First, the good: the 1L box seemed to work great, and a single piece of foam cut in half and added to the roof rack worked well to establish slightly positive buoyancy. The PWM signaling also works great (both in Cockpit and QGC). Additionally, the lights work great up to and including 50% power output. 

<p align="center">
  <img src="https://github.com/user-attachments/assets/03c42378-4e9a-4c80-8b38-234345281ca3" width="40%" />
  <img src="https://github.com/user-attachments/assets/d1381b89-30db-49db-b20d-63980a931180" width="40%" />
</p>
 
The not so good: the lights between 60-100% were VERY flickery (you can see a video from the ROV underwater with lots of flickering on [DropBox here](https://www.dropbox.com/scl/fi/8ypuzohdk2ar72ix4etrw/GX012397.MP4?rlkey=eentg91tyb1flhltrzeudnn9p&dl=0)). We were able to determine that the flickering occurs when the thrusters are being feathered (and not when the thrusters are slammed forward at full power). So, as an example, when the ROV is in depth hold or position hold underwater - whereby the thrusters are constantly firing to varying degrees - we have near continual flickering at light power outputs of 60-100%. In contrast (and as Megan and Reid tested afterwards on land), when the thrusters are slammed all the way forward (even at a thruster gain of 70%), the lights at 100% power output were steady - no flickering. 

Another oddity is the tlogs didn't appear to record properly (one is linked [here](https://www.dropbox.com/scl/fi/9cebezf7pajb5m0mesqan/2026-04-02-09-34-52.tlog?rlkey=2m78tu86l1issmw190c2exguh&dl=0)), but the .bin file seems to have recorded just fine (linked [here](https://www.dropbox.com/scl/fi/b5x63q81oe2u509s0r4ez/00000090.BIN?rlkey=i3043tfb23ozlj3ultfotmmyk&dl=0)). We have some snazzy tools to visualize power consumption from the tlogs converted to csv, but those R tools ([here](https://github.com/Seattle-Aquarium/CCR_ROV_survey_methods/issues/35)) don't extend to the .bin files. For now though, we can view the above .bin file in [UAV Log Viewer ](https://plot.ardupilot.org/#/)

Here is a shot of the ROV flight w/ volts visualized (above) and amps (below). 

<p align="center">
  <img src="https://github.com/user-attachments/assets/7843c3e4-e677-4b33-8b21-d79657bd6da2" width="90%" />
</p>

<p align="center">
  <img src="https://github.com/user-attachments/assets/8d9a9b02-8cc2-4735-9882-3c6cfc53ee5a" width="90%" />
</p>

As you can see, if you take an approximate median, 13V * 40A = 520 Watts, which aligns well with what we expected (i.e., x4 lights at 100% would pull 100 Watts each, and the ROV at 30% gain would pull an additional 100 Watts, totaling ~ 500 Watts, well within the 1000 Watt limit of the Outland Topside Power Supply system. Even at the "extreme" peak voltage drop: 12.46V * 64.26A = 800 Watts. 

Next, our other example (when Megan and Reid tested the ROV again on land), the figure is less cluttery and we can align both Volts and Amps atop one another in a single figure: 

<p align="center">
  <img src="https://github.com/user-attachments/assets/27a6bde7-2544-4b32-97bd-bab85d923e74" width="90%" />
</p>

Right at 10:00 when we see sustained power usage, the ROV thrusters were at 70-80% (WAY faster than we ran them underwater), the thrusters were at "full throttle," and the lights were at 100% . . . and there was no flickering (!!). Indeed, we see ~ 13V * 35A = 455 Watts. Then, right around 13:25 they start feathering the throttle, and we see lots of little (and not so little) jumps in Amps, which also generated flickering similar to what we saw underwater. 

So, it seems like power itself (Watts) isn't a limiting factor here, but changes in voltage or current or something else (largely from varying thruster draw) is affecting the lights when at power outputs greater than 50%. 

What do folks think??

**Comment by clydemcqueen** [comment]
* Edit1: Yay, good dive! Big milestone.
* Edit2: Wow, look at Lutris rocking the new look!

I was surprised to see the video show the flickering getting _brighter_. Were the lights mostly at the target illumination, and then they just randomly got brighter, or were you trying to get to that higher illumination level, and they just couldn't get there, except occasionally?

It would be helpful to see the PWM signals for the lights and the thrusters, so we can try to correlate the power fluctuations with the PWM signals, or something else. Is the bin file uploaded somewhere?

And we need to figure out how to get the tlog files working....

**Comment by zhrandell** [comment]
Yeah! - Lutris is now rocking the red trim that matches the Seattle Aquarium diver's drysuit, with red up top and black on the lower 2/3rd. The red was also selected due to providing a nice contrast against the dark sea surface when the vehicle is at the surface.  

Regarding flashing _brighter_, Clyde, I think your observation is correct . . . I think the lights are mostly at the correct output, but then start to flicker at brighter (and darker) levels (but again, I'm not 100% certain . . . ). 

The full bin file for the entire flight can be found [here on DropBox](https://www.dropbox.com/scl/fi/b5x63q81oe2u509s0r4ez/00000090.BIN?rlkey=i3043tfb23ozlj3ultfotmmyk&dl=0) - you should be able to download it. 

Also, note that between `10:36:40` and `10:40:19` (via `TC 25` from the GoPro Labs [time sync page](https://gopro.github.io/labs/control/precisiontime/)) Reid ran a "transect" where the lights were at 50%, and he flew forward at 0.10-0.125m/s. We originally wanted to capture power consumption metrics for this "transect" with the lights at 100%, but we backed down to 50% given the flickering behavior. 

This also leads to one caveat about the flight . . . I was a little alarmed by the flickering, so the vast majority of the time we were down there I signaled to Reid to have the lights at 50% . . . so, there will only be a few select instances within the bin log that capture the "flickering". Does the bin log capture PWM signaling? If so, that'd be very helpful to isolate thruster and power dynamics for any and all instances where the PWM was above 50%.

**Comment by amarburg** [comment]
Just to bisect the problem, it seems like it could be power-related, or it could be comms related.   I've had BlueROVs exhibit a similar coupling between lights and thrusters when the PWM control line for the lights came loose from the Navigator board.  There can be enough electrical noise from the thrusters to fool the Lumen lights into coming on.   **However** given the archictecture of the DSPL system w/ the Pico translating to serial, I wouldn't jump to the conclusion.

A first question for @keenanjohnson -- how fast does the main loop in your firmware run?   Does it update the lights fast enough to account for the flickering (by eye, it looks like ~10Hz even at the most "flickery")?   That is, could it be "real" where the Pico is seeing a spurious PWM input and commanding the lights to different levels?

**Comment by zhrandell** [comment]
Thank you for jumping in, Aaron! I can't speak to the firmware, but re: the PWM control light, per your recommendation when you were on-site with us a couple weeks back, I used a three-pin dupont connector that plugged into servo # 15 in the Navigator board. I used BR's lumen/gripper cable (22 AWG), with the other two non-PWM cables cut down towards the inside of the Wet Link Penetrator. 

However, now that I think about it, I didn't place the metal inserts into the x2 empty dupont connector ports, so I'm not sure those x2 empty connectors are providing as much extra stability as they otherwise could. If it's looking like that may be contributing, I can easily add the metal pins and re-test the lights/thrusters on the bench. We will also put eyes on servo # 15 today to see if that connection looks loose at all (and we'll report here if so).  

EDIT to note that the single lumen cable is not shielded / protected in any way, as I'm largely unfamiliar with what would be required to do so.

**Comment by clydemcqueen** [comment]
Oh, that is interesting @amarburg 

The logs don't provide much, but they do support the "comms problem" hypothesis.

Here is a graph comparing the PWM signals on RCOU.C5-C8 (the 4 vertical thrusters), RCOU.C9 (the lighting circuit, the black line), and BAT[0].Curr (the current draw, the red line). This is a zoom into a 5-minute section where RCOU.C9 is constant, but the current is spiking:

<img width="1647" height="1052" alt="Image" src="https://github.com/user-attachments/assets/47a2bcb2-f0d2-46bc-bad2-5638df140f51" />

MAVExplorer.py: `graph BAT[0].Curr:2 RCOU.C1 RCOU.C2 RCOU.C3 RCOU.C4 RCOU.C9`

These are big current spikes. I think the current sensor is only reading at ~1.6Hz (but logging at 10Hz), so there is no way to see the fine detail of the spikes.

**Comment by keenanjohnson** [comment]
Ah very interesting.

For everyone's reference, the relevant source code is here: https://github.com/Seattle-Aquarium/CCR_ROV_survey_methods/blob/7e5f8b5c9c3030da52a945fe5bf2641dd8ef978a/lighting/code/src/main.py#L271-L298.

@amarburg to your question, it runs on a 20 Hz control loop.

I agree with everyone's commentary above and I think attempting to prove whether it's power related or control signal related is a good step. 

I would also note that it is definitely possible there are bugs / improvements we can make to the firmware of the lights micro to make it more robust to control noise if that turns out to be the cause. 

Is it possible to replicate the flickering on the bench? Figuring out a reliable way to replicate would be the first step in identifying the root cause.

**Comment by zhrandell** [comment]
Thank you, everyone, for jumping in! 

@keenanjohnson, yes, we can replicate the flickering on the bench. In fact, [here's a short video](https://www.dropbox.com/scl/fi/236u1ubvpui49nkt5ts6d/original-2D721614-BC94-4309-9EB8-0DBB93A8FA66.mp4?rlkey=so0f3nw9l4iz0rzxths7oummu&dl=0) of Megan and Reid running Lutris on land - as you'll see, they replicate the issue by demonstrating (1) the flickering occurs when the thrusters are being feathered, then (2) the lights do not flicker even when at 80% power output while the thrusters (at 70% gain) are at full throttle. This can be replicated in both Cockpit and QGC.  

We are more than happy to test this further on the bench . . . please just let us know what you'd like us to try!

**Comment by amarburg** [comment]
A quick test might be to plug into the USB on the Pico and look at the serial console.   

Maybe decrease `STATUS_INTERVAL_MS` to increase the frequency of [these messages](https://github.com/Seattle-Aquarium/CCR_ROV_survey_methods/blob/7e5f8b5c9c3030da52a945fe5bf2641dd8ef978a/lighting/code/src/main.py#L295).     What do you think, @keenanjohnson ?

**Comment by keenanjohnson** [comment]
Yes, I agree with @amarburg that a good next debugging step would be to monitor the serial port output via the USB of the raspberry pi pico inside the lighting box and see if there are spurious PWM signals being received. If so, then it would seem likely that the PWM signal itself is subject to loose cables or noise. 

If we don't see those messages, my intuition is that the issue is more likely due to power fluctuations and would likely likely monitoring the output of the voltage converter with an oscilloscope to see if there are power fluctuations. 

I'm out of town for a while, but happy to write up more details instructions or debug on a call or something sometime if that's useful!

**Comment by zhrandell** [comment]
Thank you, @amarburg and @keenanjohnson! Based on briefly talking to Aaron about this on-site yesterday, it sounds like we indeed simply need to plug into the pico and monitor the PWM signals via a serial port that should be accessible. Aaron also noted that we can up the Hz via modifying a single line of code and pushing those changes to the pico, which may provide better resolution re: the potential occurence of spurious PWM signaling. 

We can definitely plug into the pico, though I'm not precisely sure how to pull up the serial port, and I haven't flashed code to the board either. But, these do seem like very basic things to do, and we should know how to do rudimentary de-bugging on the system like this, so next week we will tackle both of these items. It sounds like the start up guides likely contain this info. I'll ping folks back here if we're stuck and/or what we find. 

Thanks again!

**Comment by keenanjohnson** [comment]
Hey @zhrandell and team. I've created this more instructive document on how to debug the light system further given our suspicion is that it's control signal related. I "think" it covers the broad basics of how to edit and install the updated software on the r pi pico, but as always reach out to me if something is unclear! https://github.com/Seattle-Aquarium/CCR_ROV_survey_methods/blob/main/lighting/pwm_lights_debugging_instructions.md

**Comment by zhrandell** [comment]
@keenanjohnson, your instructions were perfect - thanks again! 

@reidtosa and I implemented them and were able to confirm that the PWN signals are indeed getting stepped on by voltage varation to the thrusters, specifically when the thrusters change (start / stop) - sustained thrust doesn't seem to elicit the same effect, as described previously.  

Reid exported a text file with the output and I've attached it below; I've also pasted a segment below. With the lights set to 90% (PWM: ~1820), we see PWM bursts up to 4593, and as low as 135 as I manipulate the thrusters. As you can see, the resulting percent power output (in this short snip) is either 100% or 0% - our flickering.


```
PWM: 1820 us | Level: 90%
PWM: 1819 us | Level: 90%
PWM: 1868 us | Level: 89%
PWM: 1820 us | Level: 89%
PWM: 1818 us | Level: 89%
PWM: 3492 us | Level: 100%
PWM: 3613 us | Level: 100%
PWM: 1858 us | Level: 90%
PWM: 2733 us | Level: 100%
PWM: 2380 us | Level: 89%
PWM: 135 us | Level: 100%
PWM: 646 us | Level: 0%
PWM: 1819 us | Level: 90%
PWM: 2224 us | Level: 90%
PWM: 1819 us | Level: 90%
PWM: 1820 us | Level: 90%
PWM: 1819 us | Level: 90%
PWM: 1768 us | Level: 90%
PWM: 3342 us | Level: 100%
PWM: 2186 us | Level: 0%
PWM: 1819 us | Level: 90%
PWM: 1821 us | Level: 90%
PWM: 464 us | Level: 0%
PWM: 1817 us | Level: 89%
PWM: 1819 us | Level: 89%
PWM: 1313 us | Level: 100%
PWM: 1816 us | Level: 90%
PWM: 965 us | Level: 100%
PWM: 1819 us | Level: 89%
PWM: 1892 us | Level: 87%
PWM: 4593 us | Level: 90%
PWM: 1819 us | Level: 90%

```

[pico_flicker_test_export.txt](https://github.com/user-attachments/files/26989210/pico_flicker_test_export.txt)

I checked the GP16 signal wire and it _seems_ fine? At the very least the connectors are secure. There's a small nick in the GP16 insulation but it doesn't reach the conductor so I assumed it was fine (I'll try replacing this wire entirely on Friday . . . easy to do via the WAGO connectors!). 

It's a bit of a birds nest in there (pic below); I can try to keep the GP16 cable isolated from the 24 V, but everything gets jostled necessarily to fit the lid on. 

Is there something I can do to increase the isolation of the GP16 wire? Would a Ferrite core be useful in this instance? Or something else? 

Thanks again!

<p align="center">
  <img src="https://github.com/user-attachments/assets/fb788fc9-7e06-4ac1-8cff-87186958b134" width="50%" />
</p>

**Comment by keenanjohnson** [comment]
@zhrandell thank you this is perfect and I am glad you were able to implement the test so quickly! It is also good to know that you are all set up with the ability to flash the rpi pico in case you ever had to swap that part or anything.

Ok the logs do seem quite clear here. There are two issues I can see:

1) There are a few confusing log entries like this: `PWM: 965 us | Level: 100%`. This is confusing because obviously 965 us does not map to 100% power. My belief is this is a bit of a software bug. Unlike normal python, micropython can have these things called "interrupts" which is what allows the r pi pico to very quickly read the PWM signal. The control loop reads pulse_width_us twice per iteration, once at main.py:281 to compute target_level, and again at main.py:291 for the print. Between those two reads the ISR fires and updates the value. So Level is the level commanded from the first read, PWM is whatever the second read captured. That is an easy bug I can fix.

that leads us to our real conclusion as to the issue: which is that the PWM signal does seem to be a bit noisy and showing some spurious values sometimes, causing the flickering. This is great news, because this is a much easier problem to fix rather than some sort of power related issues

2) To fix the spurious values, yes potentially a ferrite core or something could help, but I believe we can also implement two software features that will likely fix the issue without requiring any hardware changes:

- Many of the spurious values seem to be out of the valid PWM range, so we can add a small feature to ignore any values that fall outside of the (1100-1900 us) range. 

- We can add a simple feature to filter the values in software a bit, as they seem to be transients which cause issue. We can for example, set the lights to the median of the last 5 signal values, which should mean we ignore most transients which cause power flickering. 

Does that make sense? I'll implement those changes now and push up a new software change that you can test to see if it resolves it.

**Comment by keenanjohnson** [comment]
I created the PR above which implements the changes I described above. You'll need to do a git update (pull) and update the STATUS_INTERNAL_MS again before reflashing according to the instructions, but my hope is that this will resolve the issue without any hardware changes @zhrandell and @reidtosa .

**Comment by amarburg** [comment]
> It's a bit of a birds nest in there (pic below); I can try to keep the GP16 cable isolated from the 24 V, but everything gets jostled necessarily to fit the lid on.
> 
> Is there something I can do to increase the isolation of the GP16 wire? Would a Ferrite core be useful in this instance? Or something else?

@keenanjohnson's software fix is a good no-hardware patch.  I wonder if this is related to the [Pico2 pulldown resistor bug](https://hackaday.com/2024/08/28/hardware-bug-in-raspberry-pis-rp2350-causes-faulty-pull-down-behavior/)?  Could add an external pull-down resistor and see if that helps? 

I assume Circuitpython enables the Schmitt trigger on the input to the Pico? (they are enabled by default)

If the problem is bigger than that, we would need to scope the GP16 signals to be sure, but I would *guess* that the spurious signals are either EMI on the servo line or maybe radiated through the power ground. 

In that case, I would suggest connecting the ground from the Navigator to the Pico in parallel to the servo signal.  Unfortunately, this would form a ground loop;  I would solve this with an isolated RS485 transceiver (so the Pico is on the Navigator ground while the lights are on the power ground).    Adds complexity.

**Comment by zhrandell** [comment]
Thank you both very much, @keenanjohnson and @amarburg! 

Keenan, Reid and I just pushed your edited software to the Pico, and I'm pleased to report that it was a BIG improvement. We still see some minor flickering, but your edits have clearly tackled the vast bulk of instances. See below for the full export file (we also bumped messaging up to 50 from 100), and here's a snip with minor flickering: 

```
PWM: 1896 us | Level: 99%
PWM: 1899 us | Level: 99%
PWM: 1897 us | Level: 99%
PWM: 1897 us | Level: 99%
PWM: 1842 us | Level: 92%
PWM: 1894 us | Level: 99%
PWM: 1894 us | Level: 99%
PWM: 1894 us | Level: 99%
PWM: 1804 us | Level: 88%
PWM: 1895 us | Level: 99%
PWM: 1895 us | Level: 99%
PWM: 1896 us | Level: 99%
PWM: 1897 us | Level: 99%
```

Question . . . instead of using the median, do you think there might be value in dropping erroneous values via calculating the standard deviation (or variance)? Under normal circumstances, and within a rolling window (e.g., the previous 10 values), the sd should be effectively 0 . . . perhaps that could help drop erroneous values? I ask, perhaps a large number of back-to-back erroneous values could throw off a median, but if the rolling window is long enough, I'd expect the sd to be a good metric by which to drop values? Just an idea . . . 

[pico_flicker_test_day2.txt](https://github.com/user-attachments/files/27062252/pico_flicker_test_day2.txt)

**Comment by keenanjohnson** [comment]
Thanks for the test @zhrandell . Looking at the logs, there seem to be two styles of flickering still:

- Some dithering just a bit around a few percent. To address this, I propose increasing the lighting deadband to 5%, so that the lights values are quantized to 5% chunks, which I believe to be adequate in our case

- There are still a few bigger swings than the 5% deadband occasionally in the logs. To help prevent any of that, I also increased the median window to 9 samples  to help smooth anything else further at the cost of just a little more latency. 

These were both implemented in https://github.com/Seattle-Aquarium/CCR_ROV_survey_methods/pull/41 and @zhrandell has confirmed they are retesting now.

**Comment by zhrandell** [comment]
Okay folks, we implemented @keenanjohnson's latest software edits, tested once more (no flickering observed on the bench!), sealed up the box, pressure tested, and flew the ROV off the side of the pier for a real-world test. The results were . . . a little odd. 

The flickering has definitely improved from how bad it was the last time the ROV was underwater (see the video in the [above post](https://github.com/Seattle-Aquarium/CCR_development/issues/34#issuecomment-4181020923) if you want a refresh on what we previously observed). 

We recorded today's full flight with a downward-facing GoPro, and you can view it all [here on DropBox](https://www.dropbox.com/scl/fi/el4f7mpeqjoeik0wajaq2/GX012069.MP4?rlkey=4k9qsd8vmb2aeelbs3bsgvc6j&dl=0). Specifically, if you skip to `7:40`, you'll see the flickering from today at its "worst". Definitely an improvement, but definitely still flickering. 

To deepen the mystery, upon pulling the ROV out of the water, and prior to powering off, we once more powered the lights to 100% and ran the thrusters . . . no flickering (just as when we tested on the bench prior to the flight . . . [see for yourself here](https://www.dropbox.com/scl/fi/jnumg5ryut4fr4ljzwivu/IMG_1656.MOV?rlkey=m005pahz7rg03431kl3lyq2h6&dl=0)). 

The good news is that Keenan's updates have improved the flickering . . . the bad news is that we can no longer reproduce the flickering on the bench, but it still manifests at depth when flying.  

Aside from the flickering, it was a really odd flight . . . depth hold, surftrak, and position hold all had issues at times . . . I was particularly surprised when in position hold to see the ROV lurch forward / downward. The full BIN file from that flight is [here on DropBox](https://www.dropbox.com/scl/fi/ch3ap0ibi3ntdtefqyxyi/00000101.BIN?rlkey=trwrilrchwk58euh3gn166gap&dl=0). In the image below you can see us switching across flight modes trying to find something stable. Both "manual" and "stabilize" seemed to consistently work okay. 

<img width="2952" height="1362" alt="Image" src="https://github.com/user-attachments/assets/0e35c0c2-2a5b-46dd-b8ed-3b6946064b33" />

**Comment by keenanjohnson** [comment]
Thanks for the update and all the test @zhrandell ! It is good that we have improved the lighting flickering on the bench, which means we are moving int he correct direction, but obviously it's not good that it still happens underwater.

A few theories:

1. The vibration or electromagnetic noise that affects the PWM signal is MUCH worse when flying underwater vs on the bench due to the ROV actually moving around or the thrusters actually pulling significant current to move around in water. If this were to be the case our root cause would be that the PWM signal to the ROV is just way too noisy still for our current filter in software we have implemented
2. Something is happening with the strobe pin or chassis wires of the lights which only manifests underwater. Am I remembering correctly that those lines didn't fit through the wet link penetrators, so there is some, but not zero chance a little moisture intrudes onto those lines.

Personally it still seems like option 1 is most likely given what we know. @amarburg proposed one method of investigation above via an osciliscope on the bench. Another would be to add some features to log a file of the PWM signals during flight onboard the light controller to see if the noise is worse in flight. Those are both diagnostic tools to help us identify the problem, but I am growing somewhat wary that the PWM signal is even the correct choice for us here.

I had originally chosen PWM as a output because it would be "easy" and wouldn't require changing the software on the navigator / ardupilot. However, an option that @clydemcqueen proposed way back in his original investigation document was to instead write a new component that runs on the navigator and sends a serial (digital) signal from the navigator to the ligthing microcontroller. This should be almost impervious to things like error from electrical noise and would allow for bi directional communication as well. I am starting to wonder if it's time to implement that instead of continuing to fight the PWM signal.

A second more hacky option would be to increase the deadband levels if you just need something working asap @zhrandell . For example we could increase the deadband to 25% given you four power levels, but I'm not sure if that accomplishes your goals.

**Comment by zhrandell** [comment]
Thank you, @keenanjohnson! I really appreciate how thoughtful you guys are at proposing steps to debug the PWM (re: your and @amarburg's comments above) and potentially exploring alternative signals, as you just did. 

To your question about the chassis and strobe wires getting snipped as they didn't fit through the 8.5mm WLP, you are correct, but they are upstream of the WLP compression seal, so unless we had a leak (and our pressure test holds solid at 15mmHg), I don't think those snipped wires are getting exposed to water.

I'm completely open to exploring alternatives to the PWM signal. Keenan, in terms of timeline for the lights, looking across 2026 (and 2027), the vision for the lights are as follows: 

- measure the lights' field of view as to inform the Sony camera upgrade, specifically the discussion re: lenses, dome ports, and housing, per #40. Fortunately, this objective can be advanced with flickering lights, and I'm inclined to dive with Lutris next week to lay down x2 meter tapes and accomplish this objective. 
- finalize the light system and include it in our ROV field methods manuscript; there isn't a fixed "must submit to a journal by" date - I would love to submit by June/July if possible (the paper is 85% complete, save for the main and supplementary sections on the lights). 
- utilize ROV _Lutris_ as part of summer 2026 ROV surveys in Elliott Bay (August, September) for the Port of Seattle (_Nereo_, with the battery-powered Kraken lights, can always step in for _Lutris_). 
- have sufficient confidence in the lighting system to enable Oregon Coast Aquarium to place an order with DeepSea; OCA needs to be fully operational summer 2027, so there is some time here, but I'm mindful of the months is took to fabricate and ship our set of DeepSea lights. 

In short, I'd advocate for taking the time required to iterate and solidify the system, and if a serial / digital signal would work better against the presumed effects of EMI, I'm all for it. Could such a serial signal make use of existing cabling? e.g., the current PWM signal comes in on a 22 AWG line (the [Lumen/Gripper](https://bluerobotics.com/store/cables-connectors/pur-subsea-cable/) cable). It sounds like we'd switch from a servo connection to another port on the navigator? If so, that would be an easy swap for us once we know the particulars. 

edit: and if there is anything we want to do re: trying to log PWM signals from a real-world flight, as mentioned above I'm going to try to dive with Lutris next week to measure the lights' field of view, so we likely will have Lutris in water Wed or Thursday (4/29, 4/30) next week, just FYI.

**Comment by amarburg** [comment]
I agree with @keenanjohnson 's original design choice.  There are enough "pros" in terms of using PWM -- particularly that you can replicate all of the existing software design patterns from the Lumen lights -- that it was the right place to start.      I still think it's worth a couple of hours of investigation and maybe try to terminate or shield the PWM signal slightly better.

> Could such a serial signal make use of existing cabling? e.g., the current PWM signal comes in on a 22 AWG line (the [Lumen/Gripper](https://bluerobotics.com/store/cables-connectors/pur-subsea-cable/) cable).

Yes, in fact we can have the Pi communicate directly with the lights over RS485 using something like [this](https://www.sparkfun.com/sparkfun-usb-to-rs-485-converter.html) and remove the Pico altogether.  The "hard" part is we would need to add an extension to BlueOS to talk to the lights and take direction from Mavlink.   Not impossible, just "off the beaten track" compared to using PWM.

**Comment by zhrandell** [comment]
Thanks @amarburg! I'm game for either approach. 

Regarding the potential to debug the PWM further, Aaron and @keenanjohnson, to try to better understand the PWM signal interference, is there some way we could log PWM signals on the pico while the ROV is underwater? Can the pico log signals that we then retreive afterwards, or can we plug something into the pico, seal up the box, and retreive it afterwards?

**Comment by amarburg** [comment]
I'd say "not amazingly."   We know the Pico is getting variable/erroneous PWM signals, and could gin up a way to have it log those values (add an SD card hat to the Pico?), which might help us understand the characteristics of the noise?

But ultimately I think it's an analog problem on the PWM line.   If we can replicate it at all on the bench -- even if it's "better" because we can't rev the thrusters as much --  we learn the most by doing that test.

**Comment by keenanjohnson** [comment]
Yes I agree with @amarburg that we could add some more hardware to the Pi to include an SD card that would give us enough space to log some things on the pi, but it's not really a great piece of information and would require lots of back and forth effort enclosing and un-enclosing the lights box.

### Issue Summary

To summarize the issue, the problem seems to be that when the motors are under load (when underwater), the PWM signal is noisy enough to cause erroneous light flickering. Initially we had increased the deadband threshold and a rolling median window in this PR to address this which fixed the unloaded (ROV out of the water) issue, but the issue reproduces in the water.

There are two general ways to address this: software filtering which mitigate symptoms and physical fixes to address the root cause. We've already done a little bit of software fixes, so as @amarburg suggested it's probably time to move onto physical fixes, although you could also continue fidgetting with the deadband (LEVEL_DEADBAND) and median paramters (MEDIAN_WINDOW) in the micropython code to address the symptoms.

### Analog Fixes

Ultimately as @amarburg said, it's an analog signal problem. I have heard that you'll have access to an oscilloscope on monday, which is the best debugging tool for this kind of problem. I pulled the following screenshots of what a good and bad PWM signal should look like from this stackover flow post: https://electronics.stackexchange.com/questions/176577/how-to-clean-up-a-noisy-signal

### Clean PWM Signal

<img width="480" height="234" alt="Image" src="https://github.com/user-attachments/assets/e7820616-1383-4806-a657-34a6795fd473" />

### Noisy PWM Signal

<img width="480" height="234" alt="Image" src="https://github.com/user-attachments/assets/ff14373a-2aff-4f6f-a628-e74a04142b97" />

### Zoomed in Noisy Signal

<img width="480" height="234" alt="Image" src="https://github.com/user-attachments/assets/40a64eb7-56a0-40a9-82f8-c7c2b00c8cff" />

### Diagnosing the Issue

Although we have addressed the symptoms in software filtering while out of the water, it is my strong suspicion that if you look at the signal out of the water, you will see the noise and you can try noise fixes and check via the osciliscope before retesting underwater.

1. Since I have heard you will have access to the osciliscope, the first order is to connect it to the PWM line via a splitter or some other mechanism to view the signal
2. Try to run the thrusters and watch the light PWM signal for noise
3. Try fixes (like wiggling connectors, twisting the PWM pair lines, shielding etc) and see if anything improves the signal dramatically.
4. If you are able to get to a good place on the osciliscope, then you can restest under load, either by testing underwater or removing the thrusters and placing in buckets etc.
5. If the PWM line isn't the problem, it is still possible it's power related and you can use the osciliscope to view power under load in the same way

Does that make sense as a general strategy for testing?

**Comment by zhrandell** [comment]
Thank you very much, @keenanjohnson, this was very informative and it all makes good sense. And copy that re: it likely not being super useful to go to the effort of logging the PWM signal underwater. 

The existing cable that carries the PWM signal is from the BR's Lumen/Gripper cable (x3 22 AWG), and in an effort to streamline everything, I had previously cut back the x2 unused conductors (in hindsight, a mistake), leaving a single wire for the PWM signal.

So, I've created a new cable for the PWM signal ahead of our Monday testing. I didn't have more of the Lumen/Gripper cable, but I had plenty of the Ping cable (x4 24 AWG conductors). I've formed a twisted pair with two of them, and left the other two alone. I've left plenty of length such that we can pull the twisted pair away from the ESCs when the enclosure is open (per @clydemcqueen's suggestion) to see if that affects the PWM signal. I've obtained multiple 3mm ferrite cores, and I also have plenty of the dupont connectors for the servo on the Navigator. 

In an absolute worst case, I think this cabling could enable future serial communication. 

Thanks again, everyone, for your help . . . looking forward to debugging on Monday! 

<p align="center">
  <img width="60%" alt="Image" src="https://github.com/user-attachments/assets/79daee82-ce4a-455f-903a-2e571c1b8af5" />
</p>

**Comment by amarburg** [comment]
@zhrandell @clydemcqueen and I spent a couple of hours with Lutris yesterday, this was all testing on the bench with the light enclosure and the main ROV housing opened.  

For testing I reverted the Pico2 to commit [33c90b](33c90b90963a83bdca5106dc2ea5d5608df2ee1d) before @keenanjohnson's recent filtering changes as the old version was known to be _more_ sensitive to the flickering, with `STATUS_INTERVAL_MS = 100` for increased verbosity

We attached the scope to the PWM input to the Pico board.   I didn't do a great job of fully characterizing the noise, but here's a sample scope trace.

<img width="2016" height="1512" alt="Image" src="https://github.com/user-attachments/assets/1c2a4e95-fd85-4e30-b952-ce8f8b7411ac" />

I would say the high frequency "fuzz" was omnipresent, with the large excursion at the center of the screen being due to the thrusters.

We also observed a high number of "erroneous" PWM widths in the Pico console.

In this state, it was easy to reproduce the flickering by turning the lights up and "blipping" the thrusters.

# Attempt 1:  External pulldown resistor

I was fixated on the idea that the [RP2350 pull-down errata](https://hackaday.com/2024/09/20/raspberry-pi-rp2350-e9-erratum-redefined-as-input-mode-leakage-current/) was part of the problem.   We weren't seeing latch-down per se but it could have impacted the PWM measurement.

We installed an external 10kohm pull-down on the Pico board and [disabled the pulldown here](https://github.com/Seattle-Aquarium/CCR_ROV_survey_methods/blob/cad054f96a24422fffcdf4ac041fda8846bbfd8b/lighting/code/src/main.py#L40).   This did not seem to affect the behavior.  Removed the external resistor and re-enabled the pulldown in code.

# Attempt 2:  Twisted pair

Using Zach's ping cable above, we attached the signal (green) wire at the navigator board, and both the signal and ground (black) wires at the Pico end, to see if the twisted pair would act as a shield.     We did not terminate ground on the Navigator end as this would have created a ground loop.

Lights still flickered under the configuration.  Might have flickered slightly less?

# Attempt 3:  

Finally, we tried a more radical solution to isolate the PWM signal and Pico from the light and motor power bus.   We connected all three lines from the Navigator output (5V, PWM @ 3v3, GND) through Zach's Ping cable, and used that 5V supply and ground to power the Pico board and RS485 converter.   

<img width="951" height="566" alt="Image" src="https://github.com/user-attachments/assets/1051e246-c25c-4be9-ba55-08e700a59025" />

To do this without a ground loop, we also:

* Completely disconnected the 24V input to the pico board
* Removed the GND from the RS485 output.

This solution relies on RS485's common mode rejection to manage any ground differences between the Pico and the lights.

This seemed to work on the bench; we did not observe any flickering.

We weren't able to install the new Ping cable, so TBD whether having the cable fully installed changes behavior.

At the end of testing I also restored Pico firmware to the [current commit](cad054f96a24422fffcdf4ac041fda8846bbfd8b) with @keenanjohnson's robustness changes.

Sounds like @zhrandell will be able to test the ROV early next week.

**Comment by keenanjohnson** [comment]
This is great work @amarburg, and @clydemcqueen  and team! 

The ground loop makes sense. We had originally wired that way on the direction for Drew from Deepsea, which I found strange at the time, but he insisted in several emails that it was "correct", but that does defeat the utility of the RS-485 common mode rejection. 

Excellent work and I'm hopeful this continues to succeed in fully integrated testing. Were you able to scope the PWM after the fix 3 to observe the signal?

**Comment by zhrandell** [comment]
I'm very grateful for the debugging assistance from @amarburg and @clydemcqueen this past Monday! 

@keenanjohnson, we didn't scope the PWM after Fix 3, as we'd already been at it for several hours and needed to wrap it up, but we were monitoring the PWM via the Pico2 running the previous [33c90b](https://github.com/Seattle-Aquarium/CCR_development/issues/33c90b90963a83bdca5106dc2ea5d5608df2ee1d) software as Aaron mentioned, and it looked very steady and we didn't see any light flickering. To be safe, Aaron still bumped the Pico2 up to the [current commit](https://github.com/Seattle-Aquarium/CCR_development/issues/cad054f96a24422fffcdf4ac041fda8846bbfd8b).

I'm out of town until Friday afternoon, but I've blocked off time on my calendar to finish the ping cable install and seal up Lutris this upcoming  Monday, and then we'll test it underwater Tuesday afternoon. Fingers crossed!

**Comment by zhrandell** [comment]
Hello folks, @m-h-williams and I flew Lutris off the side of the Aquarium's Pier 59 this morning, and I'm very pleased to report that @amarburg's alternative powering of the Pico has resolved the flickering issue!! We had completely steady performance all the way up to 100% power output for the lights. 

We took the opportunity to record power consumption: we flew Lutris with the lights at 100% and the thrusters at 20, 30, 40 and 50% power, and we ran them full throttle for 5min to see if we could elicit any issues from the Outland Topside Power Supply . . . everything looked steady! 

The only oddity to report is something that I've observed for a couple months: one of the lights *occasionally* doesn't power on properly with all the others. Previously, I've found that cycling the power resolves this. Today the light was a bit more tempermental such that power cycling didn't resolve it. Instead, what we found was that repeatedly adjusting the light brightness up and down eventually nudged the light to turn on and operate properly. We did pop open the 1 L box, and all the connections are nice and snug, so I'm not sure what's going on, but I don't think it's an issue with our cable connections. 

In any case, we're thrilled that the flickering has been resolved! I'll leave this Issue open for now until (**1**) we pull the power consumption values from the BIN file (as our tlogs aren't recording?) and plot those to see how close we are to our 1000 W limit for the OTPS system, and (**2**) we conduct some more tests with the light's field of view. 

Note too that Sajan's custom light mounts have shipped from SendCutSend, so we'll have those shortly and will utilize them with future tests - they'll let us more precisely lock in the 10 degree outwards and 10 degree forwards tilt for each of the four lights (see his design [here](https://cad.onshape.com/documents/8ce98ca1f7c7d2c3aa22c09a/w/46d36c45ed5cc39922916be8/e/916156bf822f46e0598d5a76) on OnShape). 

Thanks again, @keenanjohnson, @amarburg, and @clydemcqueen for all your help with these lights . . . it has been a journey!

**Comment by keenanjohnson** [comment]
This is excellent news and I am very excited we are close to it working! Great work all!

That is strange about the light not coming on consistently. Is it the same light each time or a seemingly random light each time?

**Comment by zhrandell** [comment]
As far as I'm aware, it's been the same light each time. And it doesn't always happen - the other day when Clyde and Aaron were on-site we power cycled probably over half a dozen times and had no issues. I also didn't have any issues yesterday after sealing up the box, vacuum testing, and testing the lights, but then this morning the one light (front right) was cantankerous . . .

**Comment by keenanjohnson** [comment]
Huh very curious. Given that it is only one light and the software is identfical my suspicion is that it is somehow wiring related, but perhaps we can also improve the software to resend the current light command on a more regular cadence which should help mitigate things if the occasional serial packet is dropped.

**Comment by zhrandell** [comment]
In case it's at all helpful, @keenanjohnson, here's a short video that shows the light is at first off, then it starts blinking on/off slightly, then it finally locked in and stayed solid on. 

Once we got the ROV in the water I noticed there wasn't as much light to the front right as expected, and we flew over to the docking station, checked the live camera feed, and sure enough that same front right light was out. So, we power cycled with the ROV still underwater (letting it float up to the surface), then flew back down to the docking station, verified via the camera feed that all four lights were on, and proceeded with the rest of the flight. As far as we're aware, that one light remained on for the rest of the flight . . . 

https://github.com/user-attachments/assets/66227c91-d03f-4ce0-9bcc-fbf717d25712

**Comment by zhrandell** [comment]
I've made several modifications to the Lutris' structure. Specifically: 

- I've added Sajan's light mounts to the frame of the Payload Skid. As a refresh, you can find his design on [OnShape](https://cad.onshape.com/documents/8ce98ca1f7c7d2c3aa22c09a/w/46d36c45ed5cc39922916be8/e/916156bf822f46e0598d5a76). These mounts are pretty slick! They let us definitively lock in any desired lateral and forward light tilt angle. The mounts I ordered from SendCutSend have a 10 degree lateral and forward tilt. If field testing suggests a different angle is desireable, we can simply order a new set of the four mounts ($80) which will make use of the same holes I drilled into the skid. Cheers for customizable yet consistent lighting!  

- As I installed the mounts in the skid itself, I've removed the HDPE "bars" that I previously had on either side of the skid - we no longer (for the moment, at least) need these to enable additional attachment points. 

- Note that Sajan did design some 3D printed half-cylindar pieces to fit over the mounts to reduce drag when the ROV is moving forward (they'd attach via the fifth screw hole visable in the forward-facing shot below), but there's an aspect of the design that would need to be modified to accomodate the bolts. It's no problem to proceed with further field testing without these drag-reducing components. 

<div align="center">
  <img src="https://github.com/user-attachments/assets/be4886a7-22df-4df8-aba9-27c97de90fdd" width="47%" alt="Image" />
  <img src="https://github.com/user-attachments/assets/9977e49d-ee2d-4d62-b321-ecd6a39114e2" width="47%" alt="Image" />
</div>
 
- We're now ready to proceed with additional field testing to better understand the field of view illuminated by these lights (and their 10 degree offset angles)! I am attempting to secure permission for the ROV to fly and test in the Dome exhibit at Pier 60, as divers could easily lay two intersecting tapes, and we'd have the benefit of gathering imagery in very clear water (which we will NOT find over the side under Pier 59 right now . . . ). Additionally, if we fly in the Dome, people could observe the ROV underwater via being in the Dome exhibit itself, which will help us understand the behavior of these new lights, their angle, their behavior across various ROV altitudes, etc.

- Finally, per https://github.com/Seattle-Aquarium/CCR_development/issues/40, I've modified the ROV's feet -- we now use a 2" long, 1/4" wide 316 bolt with two 1/4" nylon nuts to "prop up" the feet. This worked well! It effectively raises the Payload Skid up off the ground 30.48mm, just shy of the 30.96mm necessary to lift the skid sufficiently to keep the 5" enclosure and dome off the ground. I can easily raise the skid further with slightly longer 316 bolts and another nylon nut. 

<div align="center">
  <img src="https://github.com/user-attachments/assets/df169797-4d6d-44c4-8625-2cb76db2b087" width="47%" alt="Image" />
  <img src="https://github.com/user-attachments/assets/1ea49440-243f-4feb-82ba-1530f5cd0303" width="47%" alt="Image" />
</div>

**Comment by keenanjohnson** [comment]
Just to recap for good records, but we discussed the light flickering on our working call yesterday. 

We decided to do a few things:

1. Try swapping the flicking light with another by disconnecting the connector at the light body itself, rather than inside the light power / control box. If the same light flickers after the swap, then we almost certainly have a defective light and we should warranty it with the vendor. If the same position flickers, then it is almost certainly a wiring issue.
2. We discussed that the software doesn't re-issue commands to the lights on a fixed frequency. It only issues a new light command on a PWM change. We could potentially update the software to issue a new command to the light on a periodic frequency to ensure that even if a light misses a specific command packet, then it will resync to the correct set point on the next cycle. 
3. This underscores the importance of the development of the new lighting PCB to eliminate the number of wiring failure points that are possible. I have started that work here and will continue it to try and get a version as soon as possible: https://github.com/keenanjohnson/deepsea-light-pcba

**Comment by zhrandell** [comment]
Hello, @keenanjohnson, thank you for these next steps! They all sound great - we're particularly excited for the custom pcb board :-) 

Re: your 1. above, we swapped the pig-tails to the problematic light (front right) with one that is working fine (rear right), and it didn't take long for front right light to power off (and then eventually back on). I believe this supports the hypothesis that we have an issue with the light itself (and not the wiring). I will thus initiate an email with DeepSea personnel about this light. 

In order to document this thoroughly, below are two photos with the pigtails swapped, depicting both the front light not working properly (left) and then it spontaneously powered on (right). 

<p align="center">
  <img width="45%" alt="Image" src="https://github.com/user-attachments/assets/b38e7cbb-c261-4ac3-a9a7-e310f12f9e39" />
  <img width="45%" alt="Image" src="https://github.com/user-attachments/assets/79411375-ba0b-435b-ab34-e67735e5ade5" />
</p>

Additionally - and again to document the issue - below are two videos (with the pigtails in their default configuration) that again depict the light manifesting the issue (1st), and working just fine (2nd). 

https://github.com/user-attachments/assets/2be02a88-75ae-48c3-9d35-b2ec61835e76 

https://github.com/user-attachments/assets/55aaa7c5-cf97-4572-bf2f-8d60c51d8829

**Comment by amarburg** [comment]
> Re: your 1. above, we swapped the pig-tails to the problematic light (front right) with one that is working fine (rear right), and it didn't take long for front right light to power off (and then eventually back on). I believe this supports the hypothesis that we have an issue with the light itself (and not the wiring). I will thus initiate an email with DeepSea personnel about this light.

Working with DSPL is the best first step -- they may just swap out the light --  but if it helps I can put the light on the bench at APL and we can do a more detailed investigation of the light and / or help with DSPL's diagnosis.

**Comment by keenanjohnson** [comment]
Yes that's an excellent learning! Do you know which serial number is the problematic light @zhrandell ? The one I had initially in testing and had some many RS-485 issues with was : 12-049-7629

I am suspicious that potentially this could be the same light which might explain some mysteries of the past if so. But that might just be me being hopeful haha.

**Comment by zhrandell** [comment]
Thanks @amarburg! 

@keenanjohnson, I had the exact same thought and wondered if our "front right" light was the same that was giving you a bit of trouble . . . it turns out, the answer is . . . no! Our problematic light is `12-049-7628` -- the (apparent) predecessor to the light you were working with.

**Comment by zhrandell** [comment]
A quick note here that after reviewing this GitHub Issue and the photos/videos of the x1 light struggling, DeepSea will replace the driver board on that light under warranty. The light went into the mail today and should arrive in San Diego early next week.

**Comment by zhrandell** [comment]
Noting here that we have our [first peek of power consumption values](https://github.com/Seattle-Aquarium/CCR_ROV_survey_methods/issues/35#issuecomment-4632760001) from the DeepSea lights during a flight with Lutris back on 5/12. We conducted multiple "transects" where we recorded start and end times with thruster output 20%, 30%, 40%, 50% -- the first two gain values (20%, 30%) we were targeting our "standard" ROV survey speed of 0.125m/s, and then we conducted 30%, 40%, and 50% gain with the throttle sustained all the way forward (hence the five separate "transects" (colors) in the visualizations). 

There are a few quirks with the data, possibly centered around the fact that (unbeknownst to us at the time) Lutris was no longer recording tlogs, and thus we converted from [mcap](https://www.dropbox.com/scl/fi/0azje8fw1umyuukpe7yb5/recorder_20260512_161658.mcap?rlkey=liuwrzg5931yd3t00f2ke0qou&dl=0) -> [tlog](https://www.dropbox.com/scl/fi/zs052v5jm4tl3eiip8a8n/recorder_20260512_161658.tlog?rlkey=zk81tt2gkfbnsfnphli5bf6or&dl=0) -> [1Hz csv](https://www.dropbox.com/scl/fi/62ersdkpdu2kmrniqweoi/V4_power_consumption.csv?rlkey=w63xlzeb6esa3ijdgqha91cnk&dl=0). (logs from the flight linked previously). These oddities are spelled out in the first link at the top of this post. 

The TL;DR - the DeepSea lights each indeed consume ~ `100W` at 100% power output, and our ratcheting up ROV thruster gain from 20 - 50% full throttle is associated with a range of `W` output from `500 - 750`, depending upon whether you believe the mcap or BIN. This also aligns with our expectation of ROV power consumption at our relatively slow survey speeds. Yay for no big surprises! 

These DeepSea power consumption values are the final data / supplementary material figures needed for our ROV field methods manuscript, so I'll use these figs for now to complete the manuscript, though we'll likely repeat this ROV test flight once the fourth DeepSea light has been fixed and returned to us.
